name: Pull Request

on:
  pull_request:

jobs:
  check:
    name: Build Integrity
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest
      - name: Run Detekt
        run: ./gradlew detekt
      - name: Assemble Build
        run: ./gradlew assemble
  uiTest:
    runs-on: macos-latest
    name: UI Tests
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - name: checkout
        uses: actions/checkout@v3
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck